### ISSUE TITLE
`s` Is Not Available in All Contexts

### ISSUE THREAD

**Issue by flosincapite** [videlais/snowman#167]
The shorthand `s` for `window.story.state` is not always available in Twine2.
 
Minimal passage to reproduce the bug:

```
<% s.f = function() { alert('hello'); } %>
<a href='javascript:void(0)' data-passage='Passage' onclick='s.f()'>Go to Passage</a>
```

This will throw an error, but

```
<% s.f = function() { alert('hello'); } %>
<a href='javascript:void(0)' data-passage='Passage' onclick='window.story.state.f()'>Go to Passage</a>
```

works fine.

**Comment by videlais** [comment]
This is annoying, but not technically an error. **s** is only available within the scope of the Underscore template system.

**Comment by flosincapite** [comment]
Got it, sorry about that! Will close.
