### ISSUE TITLE
Please update the README instructions in regards to the latest shorthands for HTML tags

### ISSUE THREAD

**Issue by baltauger** [videlais/snowman#31]
Hello

The current README lists the old Single bracket method of creating divs and spans. I had to read the code to realize that this was not the case anymore.

Kindly update the README to reflect the current shorthand behavior.

Thanks!

**Comment by videlais** [comment]
What do you mean, @baltauger? 

Using the following code --
```
[
This appears onscreen.
]{#id.className}
```
 -- will correctly create the following HTML:
```
<div id="id" class="className">
<p>This appears onscreen.</p>
</div>
```

**Comment by baltauger** [comment]
I'm sorry for not being thorough in my initial description.

Since commit 663ba97980884a1cecf2f351241c81b75b83da58 by @klembot , lines 25 to 37 of latest passage.js currently read and function otherwise. The comment before the code describes the current expected markup:
```
	/*
	Transform class, ID, hidden, and link shorthands in HTML tags.
	<a-0.class#id> becomes
	<a href="javascript:void(0)" style="display: none" class="class" id="id">
	*/

	result = result.replace(
		/<([a-z]+)([\.#\-0].*?)(?=[\s>])/gi,
		function(match, tagName, attrs) {
			return '<' + tagName + ' ' + renderAttrs(attrs);
		}
	);
```

Using the markup you mention in a story using a compiled latest version of this repository produces no result, the custom markup still visible.

The tests in passage.spec.js (added in the same commit as above) also reflect the new behavior correctly. 

If needed, I can provide replacement text for the README describing the new method.

**Comment by videlais** [comment]
I finally see the problem, @baltauger. I was testing with the version of Snowman currently bundled with Twine. Making a new build of the current source, I see the same results you reported.

If you have wording ready, make a pull request and I'll update from there.

**Comment by videlais** [comment]
I've now updated the README for both master and dev.

**Comment by baltauger** [comment]
Awesome, thanks!
