### ISSUE TITLE
Persistent player statistics 

### ISSUE THREAD

**Issue by wbalmer** [videlais/snowman#335]
Hi! My apologies if this is not the correct place to ask this question/open an issue. I'm interested in using the [player statistics example](https://videlais.github.io/snowman/2/examples/playerstatistics/snowman_player_statistics.html) in a project, and that page notes:

"Note: Elements must exist before the attempt to bind to them in order to be successful. This example uses the ready() function to achieve this with the first, starting passage."

So, the example only works on the first passage. I was just wondering if the devs had any suggestions on how to implement player statistics so that subsequent passages could call for checks like the 'testEmpathy" and "empathyResult" using the empathy statistic set in the first passage. Thanks!

**Comment by videlais** [comment]
@wbalmer I don't really answer questions about how to use Snowman for things here. The best place to try to get answers is on the Twine Discord server, sub-Reddit, or on the IntFiction forums.

The clarification in the note is explaining that the elements and attributes must exist *before* trying to use selectors to find them using jQuery. Once loaded, those (or other) selectors can appear again in other passages and the code should still work.
