### ISSUE TITLE
savehash() in Snowman 2

### ISSUE THREAD

**Issue by Pseudavid** [videlais/snowman#38]
According to the [documentation](https://videlais.github.io/snowman/2/learning/functions.html), saveHash() is a function of window.story.

In a new Snowman story I create a starting passage:

```
:: test
<% window.story.saveHash() %>
```

When playing it: `In Passage.render() using _.template(): TypeError: window.story.saveHash is not a function`

If I see the contents of window.story in the console, there is no saveHash().

I'm using Snowman 2.0.2 and tryint to use the save and restore system.

Thanks!

**Comment by videlais** [comment]
That's not currently a bug. The function save() returns the same hash that saveHash() would have in previous versions. Now, it sets the URL hash AND returns the result at the same time.

**Comment by videlais** [comment]
@Pseudavid Were you able to figure out what you needed? Did using save() work for you?

I'm still working on updating the documentation and now know I need to add some examples on this to help future people, too.

**Comment by Pseudavid** [comment]
Not completely, but I'm not really knowledgable on JS. I can ask this in the forums.

I've been able to get save links working like this:
`window.localStorage.setItem('twine-autosave',window.story.save());`

But if I put it in the story Javascript and try to make it work automatically in every passage, it breaks. Surely a mistake in my code, but I'll put it here just in case it might be a bug:
```
$(window).on('sm.passage.shown', function(event, eventObject) {
	window.localStorage.setItem('twine-autosave',window.story.save());
})
```

**Comment by videlais** [comment]
*saveHash()* has been added back as of Snowman 2.0.3.
