### ISSUE TITLE
Event Ordering for Passage link handler

### ISSUE THREAD

**Issue by Gpeschke** [videlais/snowman#39]
Currently, attaching an event to the 'click' event for links works in a non intuitive way- 
(Specifically, what I'm doing is rendering the next passage differently based on if the link is clicked while shift is down or not)

Unfortunately, when I attach my click event, it only fires after the new passage is already rendered, preventing the new passage from using said information. 

This is because events fire in the order that they were attached, and snowman attaches it's events first(before loading the story javascript). If [this click event](https://github.com/videlais/snowman/blob/master/lib/Story.js#L247) could be moved till [after the story javascrit is evaled](https://github.com/videlais/snowman/blob/master/lib/Story.js#L284), then things would work as intuitively expected.

Currently I've gotten it to work for my code by the following(less than optimal) hack:
` 
//Disable Snowman's default click event
// This is needed so that if you add a click event they happen first
// (instead of firing after the new passage has already been loaded)
$("tw-story").off( 'click', 'a[data-passage]');
`

my click handling code

`
//Restore Snowman's default click event
// So that your event fires, then the default one
// This code is copied directly from snowman's source
$("tw-story").on('click', 'a[data-passage]', function (e) {
			window.story.show(_.unescape(
				$(e.target).closest('[data-passage]').data('passage')
			));
		});
`

**Comment by videlais** [comment]
This fix has currently been added. It is part of 2.0.3 now.

**Comment by videlais** [comment]
Merged into main branch.
