### ISSUE TITLE
How to open passage from script? 

### ISSUE THREAD

**Issue by lxknvlk** [videlais/snowman#426]
I want to make a clickable link those execute a script and then open a passage. How can i do it ? Or if this is not the place, where can i ask then?

**Comment by Bagera** [comment]
Hi, this is probably not the place for these kind of issues as this is more for issues with the code base. I have found a twine sub on Reddit and then there is the documentation for Snowman.

I think the function you are searching for is Story.show(). You can pass it a passage name or id and it will replace the content in tw-passage with that of the passage you want.

**Comment by videlais** [comment]
@lxknvlk I don't really answer questions about how to do things with Snowman here. As was recommended, the Twine subreddit, Discord server, or on the IntFiction forums are better places to get a quick response to a question.

But, yes, as @Bagera pointed to, `Story.show()` is probably what you want. You would also have to add some type of listener for the click event of the element you want as well.
