### ISSUE TITLE
[Proposal] Add support to onclick custom code in links

### ISSUE THREAD

**Issue by jenkin** [videlais/snowman#510]
Twine standard links in bar or arrow form (ie. `[[text|passageName]]`) could accept a simple additional expression executed on user click before next passage rendering (ie. `[[text|passageName][onClickCallback]]`).

It can be very useful to set a variable value (ie. `[[text|passageName][s.myVar=1]]`) or run a custom function (ie. `[[text|passageName][s.myFunc(event, this)]]`) that depends on user choice.

Syntax is inspired by [SugarCube v2 link feature](http://www.motoslave.net/sugarcube/2/docs/#markup-link).

[Here](https://github.com/videlais/snowman/compare/master...jenkin:iceman:feature/custom-onclick-in-links) is the working code, I can open a PR if ok for you.

**Comment by videlais** [comment]
I like this idea, but not necessarily the approach. As the SugarCube documentation notes, this breaks how Twine 2 understands passage links, which is not ideal behavior.

Something I have been considering is `Story.link(text, callback, passageName)` where a user could create a link with a callback, which they could define when they describe the link, and an optional passage name. This would work like SugarCube's `<<link>>` macro.

**Comment by videlais** [comment]
@jenkin After playing around with this more, I have changed my mind and decided to add it to Snowman. Your proposal has now been merged.
