### ISSUE TITLE
A lot of `index.html` files in `test/` subfolders after `npm run test`

### ISSUE THREAD

**Issue by jenkin** [videlais/snowman#514]
If you don't want to commit these files, you can consider to add `.gitignore` files in Cookbook and RunScript folders for `index.html` files.

**Comment by videlais** [comment]
@jenkin If the tests run correctly, they are removed at the end of each. This is not an issue.

**Comment by jenkin** [comment]
Ok, I figured out what's happened... I ran `npm run test -- -t Markdown` to test only my changes related to links and with the `-t` option all html files are produced but never deleted.
