### ISSUE TITLE
Error if global javascript contains `<% %>` in comments

### ISSUE THREAD

**Issue by jenkin** [videlais/snowman#516]
To reproduce this issue, simply add the this comment in global javascript: `/* <% %> */`.

It raises `Uncaught Error: Error compiling template code: Error: Could not find matching close tag for "<%".` in console on Test or Play.

**Comment by videlais** [comment]
This is now fixed. Pseudo-global properties have changed, but including tags within comments in Story JavaScript will no longer cause an error.
